language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk11

addons:
    sonarcloud:
        organization: "tegonal"
        token:
            secure: $SONAR_TOKEN

before_install:
  - chmod +x gr

install: true

script:
    - ./gr -i build
    - |
        if [ "$TRAVIS_TEST_RESULT" == 0 ] && [ "$TRAVIS_JDK_VERSION" == oraclejdk8 ]; then
            ./gr detekt
            sonar-scanner \
                -Dsonar.projectVersion=0.3.0-SNAPSHOT \
                -Dsonar.projectKey=tegonal_atrium-ktor \
                -Dsonar.kotlin.detekt.reportPaths=build/reports/detekt/detekt.xml \
                -Dsonar.sources="\
                    client/atrium-ktor-client-common/src/main/kotlin, \
                    " \
                -Dsonar.tests="
                    client/atrium-ktor-client-common/src/test/kotlin, \
                    atrium-ktor-server-tests/src/test/kotlin, \
                    " \
                -Dsonar.coverage.jacoco.xmlReportPaths="
                    client/atrium-ktor-client-jvm/build/reports/jacoco/report.xml, \
                    atrium-ktor-server-tests/build/reports/jacoco/report.xml, \
                    "
        fi

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/wrapper/
    - $HOME/.gradle/caches/
