version: "{branch} {build}"

build:
  verbosity: detailed

init:
  - set GRADLE_OPTS="-Dorg.gradle.daemon=false -Pkotlin.incremental=false"

build_script:
  - gr.bat assemble

test_script:
  - gr.bat build

cache:
  - C:\Users\appveyor\.gradle\wrapper
  - C:\Users\appveyor\.gradle\caches

environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk9
    - JAVA_HOME: C:\Program Files\Java\jdk10
    - JAVA_HOME: C:\Program Files\Java\jdk11
    - JAVA_HOME: C:\Program Files\Java\jdk12

matrix:
  fast_finish: true